[information]
 name = "organicgreen"
 background = "light"
 author = 'Kostafey <kostafey@gmail.com>'

[palette]
 fg = '#326B6B'
 bg = '#f0fff0'

 cursor_fg = '#225522'
 cursor_bg = '#D3F0D5'
 highlight = '#F0F0A1'

 dark_black    = '#24292E'
 black         = '#2e3436'
 dark_gray     = '#444d56'
 gray          = '#7f7f7f'
 light_gray    = '#b2bdb1'
 dark_white    = '#cccccc'
 white         = '#eeeeec'

 red           = '#ef2929'
 orange        = '#ce5c00'
 yellow        = '#b8860b'
 sun           = '#859900'
 green         = '#119911'
 cyan          = '#00A89B'
 teal          = '#0D7579'
 blue          = '#0065CC'
 violet        = '#5544EE' 
 purple        = '#912CEE' 
 magenta       = '#d33682'

[Editor]
Normal = 'fg bg'
Cursor = 'cursor_fg cursor_bg'
CursorLine = '- cursor_bg'
LineNr = 'light_gray -'
CursorLineNr = 'black'
Whitespace = 'bg'
EndOfBuffer = 'bg'
NonText = 'bg'
Visual = '- highlight'

MatchParen = '- highlight'

[StatusLine]
StatusLine = 'dark_black dark_white'
StatusLineNC = 'dark_black dark_white'
StatusLineSeparator = 'dark_white'
StatusLineTerm = 'dark_white'
StatusLineTermNC = 'dark_white'

[Code]
Comment = 'gray'
Variable = 'black'
String = 'green'
Character = 'sun'
Number = 'black'
Float = 'black'
Boolean = 'black'
Constant = 'black'
Type = 'black'
Function = 'purple'
Keyword = 'blue'
Conditional = 'purple'
Repeat = 'purple'
Operator = 'fg'
PreProc = 'purple'
Include = 'purple'
Exception = 'purple'
StorageClass = 'yellow'
Structure = 'yellow'
Typedef = 'purple'
Define = 'purple'
Macro = 'purple'
Debug = 'red'
Title = 'yellow'
Label = 'black'
SpecialChar = 'sun'
Delimiter = 'fg'
SpecialComment = 'fg'
Tag = 'red'
Bold = '- - b'
Italic = '- - i'
Underlined = '- - u'
Ignore = 'cyan - b'
Todo = 'blue - b'
Error = 'red - b'
Statement = 'purple'
Identifier = 'fg'
PreCondit = 'purple'
Special = 'orange'
