[information]
 name = "organicgreen"
 background = "light"
 author = 'Kostafey <kostafey@gmail.com>'

[palette]
 fg = '#326B6B'
 bg = '#f0fff0'

 cursor_fg = '#225522'
 cursor_bg = '#D5F0D5'
 highlight = '#F0F0A1'
 highlight_green = '#C1F3CA'
 highlight_gray =  '#E3F2E1'
 highlight_blue =  '#acd7e5'

 dark_black    = '#24292E'
 black         = '#2e3436'
 dark_gray     = '#444d56'
 gray          = '#7f7f7f'
 light_gray    = '#b2bdb1'
 dark_white    = '#cccccc'
 white         = '#eeeeec'

 red           = '#ef2929'
 orange        = '#ce5c00'
 yellow        = '#b8860b'
 sun           = '#999900'
 green         = '#119911'
 cyan          = '#00A89B'
 teal          = '#0D7579'
 blue          = '#0065CC'
 violet        = '#5544EE' 
 purple        = '#912CEE' 
 magenta       = '#d33682'

 sign_add      = '#27a745'
 sign_change   = '#2188ff' 
 sign_delete   = '#d73a49'
 fg_add        = '#54964a'
 fg_delete     = '#c95c69'

 marker_yellow = "#FFF68F"
 marker_green  = "#B7EB8F"
 marker_teal   = "#76DDBA"
 marker_blue   = "#91D5FF"
 marker_violet = "#ADC6FF"
 marker_purple = "#D3ADF7"
 marker_pink   = "#FFADD2"
 marker_red    = "#FFA39E"
 marker_orange = "#FFD591"

[Editor]
Normal = 'fg bg'
Cursor = 'cursor_fg cursor_bg'
CursorLine = '- cursor_bg'
LineNr = 'light_gray -'
CursorLineNr = 'black'
Whitespace = 'bg'
EndOfBuffer = 'bg'
NonText = 'bg'
Visual = '- highlight'

Pmenu = 'black highlight_gray'
PmenuSel = 'black highlight_blue'
WildMenu = 'black highlight_blue'
PmenuSbar = '- dark_white'
PmenuThumb = '- gray'

DiffText = 'sign_change -'
DiffAdd = 'fg_add -'
DiffChange = 'sign_change -'
DiffDelete = 'fg_delete -'
diffAdded = 'fg_add -'
diffRemoved = 'fg_delete -'
diffChanged = 'sign_change -'
diffOldFile = 'gray -'
diffNewFile = 'gray -'
diffFile = 'black -'
diffLine = 'purple -'
diffIndexLine = 'gray -'

MatchParen = '- highlight'

[StatusLine]
StatusLine = 'dark_black dark_white'
StatusLineNC = 'dark_black dark_white'
StatusLineSeparator = 'dark_white'
StatusLineTerm = 'dark_white'
StatusLineTermNC = 'dark_white'

[Code]
Comment = 'gray'
Variable = 'black'
String = 'green'
Character = 'sun'
Number = 'black'
Float = 'black'
Boolean = 'black'
Constant = 'black'
Type = 'black'
Function = 'blue'
Keyword = 'purple'
Conditional = 'purple'
Repeat = 'purple'
Operator = 'fg'
PreProc = 'purple'
Include = 'purple'
Exception = 'purple'
StorageClass = 'yellow'
Structure = 'yellow'
Typedef = 'purple'
Define = 'purple'
Macro = 'purple'
Debug = 'red'
Title = 'yellow'
Label = 'black'
SpecialChar = 'sun'
Delimiter = 'fg'
SpecialComment = 'fg'
Tag = 'red'
Bold = '- - b'
Italic = '- - i'
Underlined = '- - u'
Ignore = 'cyan - b'
Todo = 'blue - b'
Error = 'red - b'
Statement = 'purple'
Identifier = 'fg'
PreCondit = 'purple'
Special = 'purple'

[Git]
SignColumn = '- bg'
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'sign_add'
GitSignsChange = 'sign_change'
GitSignsDelete = 'sign_delete'

[Neogit]
NeogitBranch = 'green'
NeogitRemote = 'yellow'
NeogitHunkHeader = 'purple -'
NeogitHunkHeaderHighlight = 'purple cursor_bg'
NeogitDiffContextHighlight = 'fg cursor_bg'
NeogitDiffDelete= 'fg_delete -'
NeogitDiffDeleteHighlight = 'fg_delete cursor_bg'
NeogitDiffAdd = 'fg_add -'
NeogitDiffAddHighlight = 'fg_add cursor_bg'

[Hop]
HopNextKey = '- marker_yellow'
HopNextKey1 = '- marker_yellow'
HopNextKey2 = '- marker_green'
HopUnmatched = 'dark_gray'

[Vim-illuminate]
IlluminatedWordText = '- highlight_green'
IlluminatedWordRead = '- highlight_green'
IlluminatedWordWrite = '- highlight_blue'

[TreeSitter]
TSField = 'fg'
TSKeyword = 'purple'
TSKeywordFunction = 'purple'
TSFunction = 'blue'
TSProperty = 'blue'
TSTextReference = 'red'

[LSP]
# LspTrouble
TroubleText = 'red'
TroubleCount = 'red'
TroubleNormal = 'red'

# LspSaga
DiagnosticError = 'red highlight_gray'
DiagnosticWarn = 'orange highlight_gray'
DiagnosticWarning = 'orange highlight_gray'
DiagnosticInfo = 'blue highlight_gray'
DiagnosticInformation = 'blue highlight_gray'
DiagnosticHint = 'gray highlight_gray'

DiagnosticSignError = 'red'
DiagnosticSignWarn = 'orange'
DiagnosticSignWarning = 'orange'
DiagnosticSignInformation = 'yellow'
DiagnosticSignInfo = 'yellow'
DiagnosticSignHint = 'gray'

DiagnosticFloatingError = 'red'
DiagnosticFloatingWarn = 'orange'
DiagnosticFloatingInfo = 'yellow'
DiagnosticFloatingHint = 'gray'

DiagnosticUnderlineError = '- - u red'
DiagnosticUnderlineWarn = '- - u orange'
DiagnosticUnderlineInfo = '- - u yellow'
DiagnosticUnderlineHint = '- - u light_gray'

LspDiagnosticsDefault= 'purple'
LspDiagnosticsDefaultError = 'red'
LspDiagnosticsDefaultWarning = 'orange'
LspDiagnosticsDefaultInformation = 'yellow'
LspDiagnosticsDefaultInfo = 'yellow'
LspDiagnosticsDefaultHint = 'gray'
LspDiagnosticsVirtualTextError = 'red'
LspDiagnosticsVirtualTextWarning = 'orange'
LspDiagnosticsVirtualTextInformation = 'yellow'
LspDiagnosticsVirtualTextInfo = 'yellow'
LspDiagnosticsVirtualTextHint = 'gray'
LspDiagnosticsFloatingError = 'red'
LspDiagnosticsFloatingWarning = 'orange'
LspDiagnosticsFloatingInformation = 'yellow'
LspDiagnosticsFloatingInfo = 'yellow'
LspDiagnosticsFloatingHint = 'gray'
LspDiagnosticsSignError = 'red'
LspDiagnosticsSignWarning = 'orange'
LspDiagnosticsSignInformation = 'yellow'
LspDiagnosticsSignInfo = 'yellow'
LspDiagnosticsSignHint = 'blue'
LspDiagnosticsError = 'red'
LspDiagnosticsWarning = 'orange'
LspDiagnosticsInformation = 'yellow'
LspDiagnosticsInfo = 'yellow'
LspDiagnosticsHint = 'gray'
LspDiagnosticsUnderlineError = '- - u'
LspDiagnosticsUnderlineWarning = '- - u'
LspDiagnosticsUnderlineInformation = '- - u'
LspDiagnosticsUnderlineInfo = '- - u'
LspDiagnosticsUnderlineHint = '- - u'
LspReferenceRead = '- black'
LspReferenceText = '- black'
LspReferenceWrite = '- black'
LspCodeLens = 'gray - i'
LspCodeLensSeparator = 'gray - i'

